Repository WELLCOME-DEV-WORKS/korea-visa, pull requests merged in 2024-11, with the labels that each got.

#11 Feat/header :헤더 생성
  public/img/Logo.png
  src/app/Investment/KI_Landing_Global.css
  src/app/Investment/Section1.css
  src/app/Investment/Section2.css
  src/app/Investment/components/Seciont2.tsx
  src/app/Investment/components/Section1.tsx
  src/app/Investment/page.tsx
  src/app/KoreaVisa/components/KVLandingSection1.tsx
  src/app/layout.tsx
  src/app/ui/Footer.tsx
  src/app/ui/Header.tsx
  src/styles/KV_landing_global.css
Labels: bug

#30 next14.2.18 migration Setting - KoreaInvest
  .gitignore
  package-lock.json
  package.json
  public/file.svg
  public/fonts/GeistMonoVF.woff
  public/fonts/GeistVF.woff
  public/globe.svg
  public/img/Logo.png
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/Investment/components/Section3.tsx
  src/app/KoreaVisa/components/KVLandingSection1.tsx
  src/app/KoreaVisa/components/KVLandingSection2.tsx
  src/app/KoreaVisa/components/KVLandingSection3.tsx
  src/app/KoreaVisa/components/KVLandingSection4.tsx
  src/app/KoreaVisa/components/KVLandingSection5.tsx
  src/app/KoreaVisa/components/KVLandingSection6.tsx
  src/app/KoreaVisa/components/KVLandingSection7.tsx
  src/app/KoreaVisa/components/KVLandingSection8.tsx
  src/app/KoreaVisa/page.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/investment/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/ui/Footer.tsx
  src/app/ui/Header.tsx
  src/pages/investment/components/Seciont2.tsx
  src/pages/investment/components/Section1.tsx
  src/pages/investment/styles/KI_Landing_Global.css
  src/pages/investment/styles/Section1.css
  src/pages/investment/styles/Section2.css
  src/styles/KV_landing_global.css
  src/styles/KoreaVisa/KVLandingSection1.css
  src/styles/KoreaVisa/KVLandingSection2.css
  src/styles/KoreaVisa/KVLandingSection3.css
  src/styles/KoreaVisa/KVLandingSection4.css
  src/styles/KoreaVisa/KVLandingSection5.css
  src/styles/KoreaVisa/KVLandingSection6.css
  src/styles/KoreaVisa/KVLandingSection7.css
  src/styles/KoreaVisa/KVLandingSection8.css
  src/styles/Reset.css
  src/utils/GoogleAnalytics.tsx
  src/utils/MetaPixel.tsx
Labels: Next Migration

#31 GoogleTag, MetaPixel migration
  src/app/layout.tsx
  src/utils/GoogleTag.tsx
  src/utils/MetaPixel.tsx
Labels: Next Migration

#34 MetaFixel, Google Tag 에러 수정 / koreavisa 랜딩페이지 마이그레이션 / 빌드 정상화
  next.config.mjs
  src/app/koreavisa/page.tsx
  src/app/page.tsx
  src/pages/investment/components/Seciont2.tsx
  src/pages/investment/components/Section1.tsx
  src/pages/investment/styles/KI_Global.css
  src/pages/koreavisa/components/Button.tsx
  src/pages/koreavisa/components/KVSection1.tsx
  src/pages/koreavisa/components/KVSection2.tsx
  src/pages/koreavisa/components/KVSection3.tsx
  src/pages/koreavisa/components/KVSection4.tsx
  src/pages/koreavisa/components/KVSection5.tsx
  src/pages/koreavisa/components/KVSection6.tsx
  src/pages/koreavisa/components/KVSection7.tsx
  src/pages/koreavisa/components/KVSection8.tsx
  src/pages/koreavisa/styles/KVSection1.css
  src/pages/koreavisa/styles/KVSection2.css
  src/pages/koreavisa/styles/KVSection3.css
  src/pages/koreavisa/styles/KVSection4.css
  src/pages/koreavisa/styles/KVSection5.css
  src/pages/koreavisa/styles/KVSection6.css
  src/pages/koreavisa/styles/KVSection7.css
  src/pages/koreavisa/styles/KVSection8.css
  src/pages/koreavisa/styles/KV_global.css
  src/utils/GoogleTag.tsx
  src/utils/MetaPixel.tsx
Labels: Next Migration

#36 Route Groups을 이용한 페이지별 Footer color 지정
  src/app/(header-black)/layout.tsx
  src/app/(header-blue)/layout.tsx
  src/ui/Footer.tsx
Labels: Next Migration

#37 Route Groups을 이용한 페이지별 Footer color 지정 (#36)
  src/app/(header-black)/layout.tsx
  src/app/(header-blue)/layout.tsx
  src/ui/Footer.tsx
Labels: Next Migration

#44 React-Hook-Form을 활용한 회원가입 Input 컴포넌트화
  package-lock.json
  package.json
  src/app/mypage/page.tsx
  src/app/user/page.tsx
  src/pages/user/UserSignIn.tsx
  src/pages/user/UserSignUp.tsx
  src/ui/FormInput.tsx
Labels: Feature, Refactor

#45 MongoDB 연결
  package-lock.json
  package.json
  src/app/api/mongodb/route.ts
  src/app/page.tsx
  src/lib/mongodb.ts
  src/utils/DB.tsx
Labels: Feature
